### PR TITLE
feat: Manage data transactions

### PR DESCRIPTION
**Pull request by pichoemr**
Closes #

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [ ] 👍 yes
  - [x] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [x] 📓 docs.lenra.io
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by taorepoara** [comment]
The transaction is just needed for the data part. 
You should create a new class for the transaction.
When you call start transaction, the transaction is returned and you call the create doc directly from it without additional parameter.
When you call commit or cancel the initial API is returned.
You can create an abstract class that while be overrided by both Data and Transaction to make it easier.

**Comment by taorepoara** [comment]
This also must be added to the other libs. Can you create the corresponding issues @pichoemr  ?

**Comment by taorepoara** [comment]
@pichoemr I've made the changes. What do you think of it ?

**Review by jonas-martinez — APPROVED** [review]

**Comment by jonas-martinez** [comment]
Still need a review from @pichoemr

**Pull request merged**
